// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeP7LL8M4PB_pn4UBywAyKkg3gsQavEOU',
    appId: '1:2098750635:web:7fdea1a6450f8e675583ee',
    messagingSenderId: '2098750635',
    projectId: 'match-map',
    authDomain: 'match-map.firebaseapp.com',
    storageBucket: 'match-map.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjST6FDQVo_Aqq77CGI6pvreG8Bs3ccjQ',
    appId: '1:2098750635:android:9593b6c873cf24c65583ee',
    messagingSenderId: '2098750635',
    projectId: 'match-map',
    storageBucket: 'match-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYM8KBfKfVc-OcVigIRzIImUPCIVQcc6k',
    appId: '1:2098750635:ios:ded66694f3c2c3985583ee',
    messagingSenderId: '2098750635',
    projectId: 'match-map',
    storageBucket: 'match-map.appspot.com',
    iosBundleId: 'com.example.matchMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYM8KBfKfVc-OcVigIRzIImUPCIVQcc6k',
    appId: '1:2098750635:ios:b751c5de47f5961a5583ee',
    messagingSenderId: '2098750635',
    projectId: 'match-map',
    storageBucket: 'match-map.appspot.com',
    iosBundleId: 'com.example.matchMap.RunnerTests',
  );
}
